### ISSUE TITLE
Add feedback when a user attempts to add invalid input

### ISSUE THREAD

**Issue by oriondean** [alisd23/finput#11]
Some feedback needs to be given when the user is blocked from adding invalid input.

Possibly a very small vertical/horizontal shake? Some investigation will be needed to see what other things out there do!

**Comment by alisd23** [comment]
I want to be careful not too impede too much on design, like interactions and styles, so its very customiaable. So i could either add an invalid class to the element and maybe call some sort of callback passed in via options. I think that would be best
