### ISSUE TITLE
Moving digit to end of input can sometimes remove it

### ISSUE THREAD

**Issue by oriondean** [alisd23/finput#19]
Steps to reproduce:
1. Enter 1.1m
2. Blur from the field to allow it to format
2. Select the second 1 digit
3. Drag it to the end of the input
4. Notice that the input now shows 100,000.00, i'd expect 1,000,000.01

**Comment by alisd23** [comment]
But if you're dragging the one to end surely that would just remove the one from the second position, not replace it with a zero? And the one doesn't appear at the end because of the formatting set to it is 2dp, so .001 rounds to .00
