### ISSUE TITLE
Deletion Support

### ISSUE THREAD

**Issue by oriondean** [alisd23/finput#8]
The amount control should support the usage of the following deletion methods:

Pressing the backspace key should remove the previous digit or skip over the previous delimiter
- [x] Skip over
- [x] Remove previous

---
Pressing the delete key should remove the digit ahead of it, or skip over the delimiter ahead
- [x] Skip over
- [x] Remove next

---

- [x] Ctrl+backspace/delete should behave the same as backspace/delete
- [x] Selecting various digits and pressing backspace/delete should only delete the selection

**Comment by alisd23** [comment]
I suggest changing the requirements, it looks like it'll be much easier just to treat commas as normal characters when deleting and backspacing, as they do when using the arrow keys. So maybe not format the commas whilst deleting, only when valid number keys are pressed.
Thoughts?

**Comment by oriondean** [comment]
We'll introduce a configuration option to support two different behaviours when the user presses backspace while their caret position is in front of a thousand delimiter.

Behaviour 1: Move the caret position to be behind the thousand delimiter
Behaviour 2: Remove the first previous digit
